interface LevelDescriptor {
  map: string[],
  chips: number,
  actions: number[][][]
}

export const LEVELS: LevelDescriptor[] = [
  {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '          XXXXX XXXXX           ',
      '          X   XXX   X           ',
      '          X c XEX c X           ',
      '        XXXXXGXDXGXXXXX         ',
      '        X y B     R y X         ',
      '        X c Xb   rX c X         ',
      '        XXXXXc P cXXXXX         ',
      '        X c Xb   rX c X         ',
      '        X   R  c  B   X         ',
      '        XXXXXXYXYXXXXXX         ',
      '            X  X  X             ',
      '            X cXc X             ',
      '            X  Xg X             ',
      '            XXXXXXX             '
    ],
    chips: 11,
    actions: []
  },
  {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '         XXXXXXX                ',
      '         X  c  X                ',
      '         X     X                ',
      '         X  X  XXXXXXXXXX       ',
      '       XXX  Xa  WW     cX       ',
      '       XED  XXa WW ppP  X       ',
      '       XXX  Xa  WW     cX       ',
      '         X  X  XXXXXXXXXX       ',
      '         X     X                ',
      '         X  c  X                ',
      '         XXXXXXX                ',
    ],
    chips: 4,
    actions: []
  }, {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '               XXX              ',
      '               XEX              ',
      '           XXXXXDXXXX           ',
      '           X24444444X           ',
      '           X2XXXXXX8X           ',
      '        XXXX2XWWWWX8XXXX        ',
      '        X2444XWicWX8444X        ',
      '        X2XXXXWWWWXXXX8X        ',
      '        X2X7II    FFFX8X        ',
      '        X2XIfX    F5FX8X        ',
      '        X2XIcX P  FcFX8X        ',
      '        X2X1II  w FFFX8X        ',
      '        X2XXXX    XXXX8X        ',
      '        X66666888666668X        ',
      '        XXXXXX8c88XXXXXX        ',
      '             X8888X             ',
      '             XXXXXX             '
    ],
    chips: 4,
    actions: []
  }, {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '    XXXXXXXXX                   ',
      '    XX  T  cXXXXXXXXXXXXXX      ',
      '    Xt X XXXXX     X  S  X      ',
      '    XX     XXXDXXE X  X cX      ',
      '    XXXXXX tX   XXXX qXXXX      ',
      '    XX  T  XX P X  Q  X  X      ',
      '    Xt X XXXX   X  X  Q cX      ',
      '    XX            qXXXXXXX      ',
      '    XXXXXXXXXXX X  X  Q cX      ',
      '        X       X  S  X  X      ',
      '        X U U XXXXXX qXXXX      ',
      '        X  V  X    X  X cX      ',
      '        X U U X    X  S  X      ',
      '        X     X    XXXXXXX      ',
      '        XXXXXXX                 '
    ],
    chips: 9,
    actions: []
  }, {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '          XXXXXXXXXXX           ',
      '          XEz       X           ',
      '          XXX  zzz  X           ',
      '            X   jzo X           ',
      '            X  zzz  X           ',
      '            X  zzz  X           ',
      '            X   jzo X           ',
      '            X  zzze X           ',
      '            XXRXXXXXXXX         ',
      '            X   q     X         ',
      '            X XXXXX X X         ',
      '            X   Sus X X         ',
      '            XXXXXXXXX X         ',
      '            XWrF      X         ',
      '            XW F  h   X         ',
      '            XW F    P X         ',
      '            X         X         ',
      '            XXXXXXXXXXX         '
    ],
    chips: 0,
    actions: [
      [[16, 8], [18, 8]],
      [[16, 11], [18, 11]],
      [[18, 16], [18, 19]]
    ]
  }, {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '        AAAAAAAAAAAAAAAAA       ',
      '        A               A       ',
      '        A               A       ',
      '        AACAACXXXXXCAAAAA       ',
      '        Ac H  X   X  J cA       ',
      '        Ac H  X   C  J cA       ',
      '        Ac H  C P X  J cA       ',
      '        Ac H  X   X  J cA       ',
      '        AAAAAAXXDXXAAAAAA       ',
      '               XEX              ',
      '               XXX'
    ],
    chips: 4,
    actions: [],
  }, {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '            XXXXXXXXXXXXXX      ',
      '            X244444444444X      ',
      '         XXXX2XXXXXXXXXX8X      ',
      '         X6c624c4444444X8X      ',
      '         X8XXKXXXXXXXX8X8X      ',
      '         X8X    X  L F8X8X      ',
      '         X8X P  Xw X F8X8X      ',
      '         X8X    X  X F8X8X      ',
      '         X8X   MXM X F8X8X      ',
      '         X8XXXXXXXXXXXXX8X      ',
      '         X8W X MXM NNX668X      ',
      '         X8W X  X  DEX8XXX      ',
      '         X8W X fXKXXXX8X        ',
      '         X8W L  X   c 8X        ',
      '         XXXXXXXXXXXXXXX        '
    ],
    chips: 3,
    actions: []
  }, {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '            XXXXXXXXXXXXXX      ',
      '            X244444444444X      ',
      '         XXXX2XXXXXXXXXX8X      ',
      '         X6c624c4444444X8X      ',
      '         X8XXKXXXXXXXX8X8X      ',
      '         X8X    X  L F8X8X      ',
      '         X8X P  Xw X F8X8X      ',
      '         X8X    X  X F8X8X      ',
      '         X8X   MXM X F8X8X      ',
      '         X8XXXXXXXXXXXXX8X      ',
      '         X8W X MXM NNX668X      ',
      '         X8W X  X  DEX8XXX      ',
      '         X8W X fXKXXXX8X        ',
      '         X8W L  X   c 8X        ',
      '         XXXXXXXXXXXXXXX        '
    ],
    chips: 3,
    actions: []
  }, {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      'XXXXXXXXXXXXXXXXXXXXX           ',
      'XXXXXXXXXXXXXXXXXXXXX           ',
      'XXOOOOOOOOOOOOOOOOOXX           ',
      'XXOOZZZZZZZZZZZZZOOXX           ',
      'XXOOZZZZZZZZZZZZZOOXX           ',
      'XXOOZZ         ZZOOXX           ',
      'XXOOZZ         ZZOOXX           ',
      'XXOOZZ         ZZOOXX           ',
      'XXOOZZ         ZZOOXX           ',
      'XPOOZZ   dc    ZZOODE           ',
      'XXOOZZ         ZZOOXX           ',
      'XXOOZZ         ZZOOXX           ',
      'XXOOZZ         ZZOOXX           ',
      'XXOOZZ         ZZOOXX           ',
      'XXOOZZZZZZZZZZZZZOOXX           ',
      'XXOOZZZZZZZZZZZZZOOXX           ',
      'XXOOOOOOOOOOOOOOOOOXX           ',
      'XXXXXXXXXXXXXXXXXXXXX           ',
      'XXXXXXXXXXXXXXXXXXXXX           '
    ],
    actions: [],
    chips: 1,
  }, {
    map: [
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      'XXXOOOOOOOOOOOOXXXXXXXXXXXXEXXXX',
      'XXXO  a  a  a OXXXXXXXXXXXX XXXX',
      'XXXOacOOOOOOOOOXXXXXXXXXXX o   X',
      'X  O  a  a  a O D            & X',
      'X XOOOOOOOOOcaOXXXXXXXXXXX  j  X',
      'X XO a  a  a  OI9XX7III9XX  p  X',
      'X XOOOOOOOOOOOOXIXXIXXXIXX     X',
      'X XXXXX XXXXXXXXIXXIXbXIXXXXXXXX',
      'X XXXXX XXcXXXXX1II3X X1IIIII9XX',
      'X XXXXX XX XXXXXXXXXX XXXXXXXIXX',
      'X XXX   X   XXX      é      XIXX',
      'X XXX XXX X XXX XXXXX XXXXX XIXX',
      'X XXX  p p  XXX XyBQ   QGrX XIXX',
      'X X   p p   X X(XXXXX XXXXX&XIXX',
      'X X X XXXXXXX X XgYS   SRIIII3XX',
      'X X   zzzz zzUX XXXXX XXXXX XXXX',
      'X XXXXXXXX  c X      è      XXXX',
      'X     XXc  zz XXXXXXX XXXXXXXXXX',
      'X AAA XXXXXXXXXXrXXXXqXXXXXXXXXX',
      'X AcA XXXXXXXXXXIXXXX8XXXXXXXXXX',
      'X ACA XXXXXXXXXXIXXXX XXXXXXXXXX',
      'X     X 2XXXXXXXIXXXFIFFFFFFFFFX',
      'XXXXXXX 22XXXXXXIX RIIIIIIII IFX',
      'XP   cY 222X       XFII III IIFX',
      'XXX XXX 222A   p XXXFI I IIIIIFX',
      'X è   X 222A  p  XXXFII IIcII FX',
      'X     X 222C p p XXXF III IIIIFX',
      'X  y  X8444A     XXXFI IIII IIFX',
      'X     XXXXXXXXXXXXXXFIII III IFX',
      'X   é XXXXXXXXXXXXXXFIIII III FX',
      'XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFX'
    ],
    actions: [
      [[28, 5], [27, 3]]
    ],
    chips: 9,
  }, {
    map: [
      ' F XXXXXXXXXXXXXXX XXX F XXXXX  ',
      'XPX               X   F X     F ',
      'X X X  XXXXXXXX F X F   X F F  X',
      'X X X X        F   F F  X  F X X',
      'X  F  X  XX  F        F X    X X',
      'X     X X  F  X XXX  F   XXXX  X',
      'X F XX  X F  XX    F  F        X',
      'X  F X  X  F   XXXX  X  X  F F X',
      ' X    F X F F        X  X X F F ',
      ' XXX X  X  F F XXXXXXXXX  X    X',
      'X    X  X                 X F  X',
      'X X F  X X X XXXXXXXXXXXX X  F X',
      'X X  F X  X X            F  F  X',
      'X X F          F F F F    F  F X',
      'X X  XXXXXXX XX F F F F  F  F  X',
      'X X         F          X  F  X X',
      'X X  F F F F   F F F F X F F X X',
      'X  XX F F F F X F F F  X  F  X X',
      'X             X     EF X F   X X',
      'X XXXX XXXXXXX   XXXX  X  F F  X',
      'X     F         X      X F   X X',
      ' XXX   XXXXXXX  X XXX  X  XX X X',
      'X   X         F X    X X     X X',
      'X X X XX XX  F  X F XX X F F X X',
      'X X X   X  F  F  F F  F F F F  X',
      'X X X F X F  X               F X',
      'X  F F  X    XXXXXXXXXXXX XXX  X',
      'Xa       XXXX                  X',
      'X F F F F      XXXXXXXXXXXXXXX X',
      ' F F F F   XXXX                X',
      'F         F     F F F F F F F F ',
      ' XXXXXXXXX XXXXX F F F F F F F  '

    ],
    chips: 0,
    actions: []
  }, {
    map: [
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      'Xc     IIIIIIIIIIIIIIIIII    D  ',
      'XXXXXXXXXXXXXXXIXXXXXXXXXXXXXXX ',
      'Xc     WWWWWWWXIXFFFFFFFF    cX ',
      'XXXXXXXXXXXXXWXIXFXXXXXXXXXXXXX ',
      'XXXXXXXXXXXXXWXIXFXXXXXXXXXXXXX ',
      'X       X   XWXIXFX           X ',
      'X XXXXX2X X XWXIXFX XXXXXXXXX X ',
      'X   X   X X XWXIXFX   X       X ',
      'XXX X&r X X XWXIXFXXX X XXXXX8X ',
      'X   X   X X XWXIXFX   X X   6 X ',
      'X XXX2XXX X XWXIXFX XXX X beX X ',
      'X X       X XWXIXFX X 4 6   X X ',
      'X X XXX8XXX XWXIXFX X XXXXXXX X ',
      'X X X   X   XWXIXFX 4 X   X   X ',
      'X X X X2X2XXXWXIXFXXX X X X XXX ',
      'X   X X   XwB     RfX   X X   X ',
      'X XXX XXX XXX  P  XXXXXXX8XXX X ',
      'X2X   6 X   4     6         X X ',
      'X X XXX XXX2X8XYX2XXX XXXXX8X X ',
      'X 6 X X X   X XiX X   X     X X ',
      'X X XXX X XXX XXX X XXX X XXX X ',
      'X X 6   X   6     X   4 X2X   X ',
      'X XXX XXXXX X XXXXXXX X X X XXX ',
      'X   X X 6   X X   4   X X 4 XE  ',
      'X X X X X XXX X XXXXXXX X XXXXXX',
      'X X X   X X 6    4  X   X     XX',
      'X2X XXXXX X XXXXXXX X XXXXXXX XX',
      'X X       X   X   X X       X2XX',
      'X XXXXXXX8XXX Xay X XXXXXXX8X XX',
      'X          6  O   O   6       XX',
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    ],
    chips: 3,
    actions: []
  }, {
    map: [
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      'XccccccccccccccccccccccccccccccX',
      'XccccccccccccccccccccccccccccccX',
      'XccccccccccccccccccccccccccccccX',
      'XccccXcccccccXXXXXXcccccccXccccX',
      'XcccXXccccccccccccccccccccXXcccX',
      'XccccccccccccccccccccccccccccccX',
      'XccccccccccccccccccccccccccccccX',
      'Xccccccc       P        cccccccX',
      'Xccccccc cccccccccccccc cccccccX',
      'Xccccccc cccccccccccccc cccccccX',
      'Xccccccc cccccccccccccc cccccccX',
      'Xccccccc cccccccccccccc cccccccX',
      'XcccXccc cccccccccccccc cccXcccX',
      'XcccXccc cccccXDDXccccc cccXcccX',
      'XcccXccc cccccXEEXccccc cccXcccX',
      'XcccXccc cccccXEEXccccc cccXcccX',
      'XcccXccc cccccXDDXccccc cccXcccX',
      'XcccXccc cccccccccccccc cccXcccX',
      'Xccccccc cccccccccccccc cccccccX',
      'Xccccccc cccccccccccccc cccccccX',
      'Xccccccc cccccccccccccc cccccccX',
      'Xccccccc cccccccccccccc cccccccX',
      'Xccccccc       dd       cccccccX',
      'XccccccccccccccccccccccccccccccX',
      'XccccccccccccccccccccccccccccccX',
      'XcccXXccccccccccccccccccccXXcccX',
      'XccccXcccccccXXXXXXcccccccXccccX',
      'XccccccccccccccccccccccccccccccX',
      'XccccccccccccccccccccccccccccccX',
      'XccccccccccccccccccccccccccccccX',
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    ],
    chips: 652,
    actions: []
  }, {
    map: [
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      'XIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIX',
      'XIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIX',
      'XIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIX',
      'XIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIX',
      'XIIIIIIIIIII7IIIIIIIIIII9IIIIIIX',
      'XIIIIIIIIIIIIIII III7IIII9IIIIIX',
      'XIIIIIIIIII7IIIIIIIIIIIII3IIIIIX',
      'XIIIIIIIIII1IIIIIIIIIIIII9IIIIIX',
      'XIIIIIIIIII7IIII97I9I7III3IIIIIX',
      'XIIII7I9II II 7III9II1III9IIIIIX',
      'XIIIII7IIIII 9I7II IIII9IIIIIIIX',
      'XIIII1IIII9IIII1IIIIIII3I1I9IIIX',
      'XIIIIII13II1III9IEI13 II19IIIIIX',
      'XIIII7II97 9II1 II IIII97I9IIIIX',
      'XIIII1 9IIIIIII137II979I123IIIIX',
      'XIIIIIXIIIIIIIII7I37I4III3IIIIIX',
      'XIIII79II1II3I7III9II13I7II3IIIX',
      'XIIII6II3IIII1II3II1 IIII9IIIIIX',
      'XIIII13I79II7IIII3191II3IIIIIIIX',
      'XIIIIIIIIIIII II7IIII9IIIIIIIIIX',
      'XIIIIIIIIII1IIIIIIIIIII91I9IIIIX',
      'XIIII7II3IIII7IIIIIIIIIIII3IIIIX',
      'XIIIII7II 3IIII7I97 9I7 9IIIIIIX',
      'XIIIIIII7379III1831 3IIXIIIIIIIX',
      'XIIIIIII1I31I31IIIIPI31I3I IIIIX',
      'XIIII166IIII6III3II1IIIII3IIIIIX',
      'XIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIX',
      'XIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIX',
      'XIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIX',
      'XIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIX',
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    ],
    chips: 0,
    actions: []
  }, {
    map: [
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      'X                              X',
      'X                              X',
      'X                              X',
      'X        XXX                   X',
      'X        XcX                   X',
      'X  XXXXXXXWX                   X',
      'X  XcWW  XWX                   X',
      'X  XXXX    X    XXXXXXXXXXXXX  X',
      'X    X  M  X    Xr  X   X  rX  X',
      'X    X    XXXX  X p X p   p X  X',
      'X    XWX  WWcX  X   X   X   X  X',
      'X    XWXXXXXXX  XX XXXRXXXXXX  X',
      'X    XcX        X   X   X   X  X',
      'X    XXX        X p R M R p X  X',
      'X               X   X   X   X  X',
      'X               XXXXXXRXXX XX  X',
      'X       XXXXX   X   X   X   X  X',
      'X       X  PX   X p   p X p X  X',
      'X       XrM X   Xr  X   X   X  X',
      'X       X   X   XXXXXXXXXXXXX  X',
      'X       XXDXX                  X',
      'X        XEX                   X',
      'X        XXX                   X',
      'X                              X',
      'X                              X',
      'X                              X',
      'X                              X',
      'X                              X',
      'X                              X',
      'X                              X',
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    ],
    chips: 4,
    actions: []
  }
];
