export const LEVELS = [
  {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '          XXXXX XXXXX           ',
      '          X   XXX   X           ',
      '          X c XEX c X           ',
      '        XXXXXGXDXGXXXXX         ',
      '        X y B     R y X         ',
      '        X c Xb   rX c X         ',
      '        XXXXXc P cXXXXX         ',
      '        X c Xb   rX c X         ',
      '        X   R  c  B   X         ',
      '        XXXXXXYXYXXXXXX         ',
      '            X  X  X             ',
      '            X cXc X             ',
      '            X  Xg X             ',
      '            XXXXXXX             '
    ],
    chips: 11
  },
  {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '         XXXXXXX                ',
      '         X  c  X                ',
      '         X     X                ',
      '         X  X  XXXXXXXXXX       ',
      '       XXX  Xa  WW     cX       ',
      '       XED  XXa WW ppP  X       ',
      '       XXX  Xa  WW     cX       ',
      '         X  X  XXXXXXXXXX       ',
      '         X     X                ',
      '         X  c  X                ',
      '         XXXXXXX                ',
    ],
    chips: 4
  }, {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '               XXX              ',
      '               XEX              ',
      '           XXXXXDXXXX           ',
      '           X24444444X           ',
      '           X2XXXXXX8X           ',
      '        XXXX2XWWWWX8XXXX        ',
      '        X2444XWicWX8444X        ',
      '        X2XXXXWWWWXXXX8X        ',
      '        X2X7II    FFFX8X        ',
      '        X2XIfX    F5FX8X        ',
      '        X2XIcX P  FcFX8X        ',
      '        X2X1II  w FFFX8X        ',
      '        X2XXXX    XXXX8X        ',
      '        X66666888666668X        ',
      '        XXXXXX7c77XXXXXX        ',
      '             X7777X             ',
      '             XXXXXX             '
    ],
    chips: 4
  }
];